### ISSUE TITLE
Readme Instructions Fail

### ISSUE THREAD

**Issue by atburghardt** [Novalia/NovaliaBLE#1]
Hey,
I try to install with the instructions of the readme.
But following the Steps does'nt work, and the whole readme is'nt comprehensive.
Can you please check if this repo ist up to date?

**Comment by andrewsage** [comment]
How far through the steps do you get before it fails?
What information is missing?

**Comment by atburghardt** [comment]
I updated the podfile:

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'NovaliaBLE_Example' do
  pod "NovaliaBLE", :path => "../"
end
target 'NovaliaBLE_Tests' do
  pod "NovaliaBLE", :path => "../"
end`

and had to change one Method in the Code to:
`-(void)startDiscovery {
    self.launchDiscoveryTimer = [NSTimer scheduledTimerWithTimeInterval:30.0 target:self selector:@selector(stopDiscovery) userInfo:nil repeats:NO];
    [self.interface startDeviceDiscovery:@"novppia1"];
}`

Had to add an input-String to the startDeviceDiscovery function. Took the "novppia1" String from further down the readme. 

The App starts now, and I think its connecting to my Testboard at some point. But there is no log or anything for when i press Buttons on the Board.

`2017-04-03 16:16:32.388962 NovaliaBLE_Example[5375:2261563] YES Recognized as Novalia service: {
    kCBAdvDataIsConnectable = 1;
    kCBAdvDataLocalName = novppia1;
    kCBAdvDataServiceUUIDs =     (
        "03B80E5A-EDE8-4B33-A751-6CE34EC4C700"
    );
}`

**Comment by andrewsage** [comment]
The repo has now been updated to the latest version as it was several versions behind the internal repo.

**Comment by atburghardt** [comment]
After changing the Podfile like before it crashes because of 

interface.diagnosticsMode = true
`@import UIKit;
#import "NOVAppDelegate.h"

int main(int argc, char * argv[])
{
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([NOVAppDelegate class]));
    }
}`


I comment it out, and the App works.

Some options like start Scanning is shown. It Discovers the Device, but doesn't connect correctly.

**Comment by andrewsage** [comment]
Which version of iOS and what iOS device are you running this on?
I've just done a clean build and it run it on an iPhone 6s plus running 10.3 and it didn't need the main.m file edited.

Once the example app gets the device's MAC address and other details it then disconnects.
If you then reconnect via the Reconnect button it will work correctly.

Due to Apple not allowing the actual MAC address to be read as part of the standard BLE service information we have had to add a separate call to get that information. As the iPhone may be detecting multiple Novalia devices it just gets the MAC address and disconnects right away so you can then list all the devices nearby. 

You then have to reconnect to the device you require.

**Comment by andrewsage** [comment]
README.md has been updated to reflect these extra instructions.

**Comment by atburghardt** [comment]
Hey, I'm using 10.11.6 on my Mac and Xcode 8.2.1. My device is a Iphone 7plus with Ios 10.0.3.

I cloned the repo again, and tried to run pod install in NovaliaBLE/Example. I still get this error:

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `NovaliaBLE_Example`..

Deleting ", :exclusive => true " in the Podfile ;
and adding the platform (platform :ios, '9.0')seems to fix it. pod install succeeds.

The App works now, thank you!
